CREATE DATABASE Dostawa;
USE Dostawa;

CREATE TABLE DOSTAWCY (
  ID_DOSTAW INT NOT NULL AUTO_INCREMENT,
  DOSTAWCA VARCHAR(50) NULL,
  ADRES1 VARCHAR(50) NULL,
  ADRES2 VARCHAR(50) NULL,
  MIASTO VARCHAR(50) NULL,
  STAN BOOL NULL,
  KOD CHAR(6) NULL,
  TELEFON VARCHAR(20) NULL,
  KONTAKT VARCHAR(50) NULL,
  TEL_WEW VARCHAR(10) NULL,
  WARUNKI TEXT NULL,
  RABAT DECIMAL(5,2) NULL,
  PRIMARY KEY(ID_DOSTAW)
);

CREATE TABLE KLIENT (
  ID_KLIENTA INT UNSIGNED NOT NULL AUTO_INCREMENT,
  KLIENT VARCHAR(50) NULL,
  NAZWISKO VARCHAR(50) NULL,
  IMIE VARCHAR(50) NULL,
  ADRES VARCHAR(50) NULL,
  MIASTO VARCHAR(50) NULL,
  STAN BOOL NULL,
  KOD CHAR(6) NULL,
  TELEFON VARCHAR(20) NULL,
  TRANSAKCJE INT NULL,
  PRIMARY KEY(ID_KLIENTA)
);

CREATE TABLE PERSONEL (
  ID_PRACOW INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NAZWISKO VARCHAR(50) NULL,
  IMIE VARCHAR(20) NULL,
  INICIAL VARCHAR(5) NULL,
  DZIAL VARCHAR(30) NULL,
  TELEFON VARCHAR(20) NULL,
  SPECJALN VARCHAR(50) NULL,
  UWAGI TEXT NULL,
  NAGRODY INT NULL,
  DATA_ZATR DATE NULL,
  STOPIEN VARCHAR(20) NULL,
  ZWOLNIONY BOOL NULL,
  PELNY_ETAT BOOL NULL,
  WYDAJNOSC DECIMAL(5,2) NULL,
  WSKAZNIK DECIMAL(5,2) NULL,
  PENSJA DECIMAL(10,2) NULL,
  STANOWISKO VARCHAR(20) NULL,
  STAZ DATE NULL,
  ADRES1 VARCHAR(50) NULL,
  ADRES2 VARCHAR(50) NULL,
  MIASTO VARCHAR(50) NULL,
  STAN BOOL NULL,
  KOD CHAR(6) NULL,
  PRIMARY KEY(ID_PRACOW)
);

CREATE TABLE TOWARY (
  ID_TOWARU INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_DOSTAW INT NULL,
  DATA_ZAMOW DATE NULL,
  NAZWA VARCHAR(50) NULL,
  OPIS TEXT NULL,
  CZAS_REALIZ INT NULL,
  CENA DECIMAL(10,2) NULL,
  IL_DO_ZAM INT NULL,
  IL_NA_STAN INT NULL,
  NIE_KONT VARCHAR(20) NULL,
  KOSZT DECIMAL(10,2) NULL,
  KOMENTARZ TEXT NULL,
  PRIMARY KEY(ID_TOWARU),
  INDEX TOWARY_FKIndex1(ID_DOSTAW)
);

CREATE TABLE TRANSAK (
  ID_PRACOW INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_KLIENTA INT UNSIGNED NULL,
  ID_TOWARU INT UNSIGNED NULL,
  DATA_TRAN DATE NULL,
  ILOSC INT NULL,
  NR_ZAM INT NULL,
  UWAGI TEXT NULL,
  FAKTURA INT NULL,
  INDEX TRANSAK_FKIndex1(ID_TOWARU),
  INDEX TRANSAK_FKIndex2(ID_KLIENTA),
  INDEX TRANSAK_FKIndex3(ID_PRACOW)
);


