= Lekcja 8 - Dokąd zmierza ów korowód - C. K. Norwida - Bema pamięci rapsod żałobny

Zad. dom.

- Znaleźć elementy poezji Norwidowej

[%hardbreaks]
.I

Czemu, cieniu, odjeżdżasz, ręce złamawszy na pancerz,
Przy pochodniach, co skrami grają około twych kolan? **—**
Miecz wawrzynem zielony, gromnic płakaniem dziś polan,
Rwie się sokół i koń twój podrywa stopę jak tancerz.
**—** Wieją, wieją proporce i zawiewają na siebie,
Jak namioty ruchome wojsk, koczujących po niebie.
Trąby długie we łkaniu aż się zanoszą i znaki
Pokłaniają się z góry opuszczonemi skrzydłami,
Jak włóczniami przebite smoki, jaszczury i ptaki,
Jako wiele pomysłów, któreś dościgał włóczniami**…**

[%hardbreaks]
.II

Idą panny żałobne: jedne, podnosząc ramiona
Ze snopami wonnemi, które wiatr w górze rozrywa,
Drugie, w konchy zbierając łzę, co się z twarzy odrywa,
Inne, drogi szukając, **c h o ć  p r z e d  w i e k a m i  z r o b i o n a…**
Inne, tłukąc o ziemię wielkie gliniane naczynia,
Czego klekot w pękaniu jeszcze smętności przyczynia.

[%hardbreaks]
.III

Chłopcy biją w topory, pobłękitniałe od nieba,
W tarcze, rude od świateł, biją pachołki służebne,
Przeogromna chorągiew, co się wśród dymów koleba,
Włóczni ostrzem o łuki, rzekłbyś, oparta pod-niebne**…**

[%hardbreaks]
.IV

Wchodzą w wąwóz i toną**…** wychodzą w światło księżyca
I czernieją na niebie, a blask ich zimny omusnął
I po ostrzach jak gwiazda spaść niemogąca prześwieca.
Chorał ucichł był nagle i znów jak fala wyplusnął**…**

[%hardbreaks]
.V

Dalej **—** dalej **—** aż kiedy stoczyć się przyjdzie do grobu
I czeluście zobaczym czarne, co czyha za drogą,
**K t ó r e  a b y  p r z e s a d z i ć,  l u d z k o ś ć  n i e  z n a j d z i e  s p o s o b u**,
Włócznią twego rumaka zeprzem, jak starą ostrogą**…**

[%hardbreaks]
.VI

I powleczem korowód, smęcąc **ujęte snem grody**,
W bramy bijąc urnami, gwizdając w szczerby toporów,
Aż się mury Jerycha porozwalają jak kłody,
Serca zmdlałe ocucą, pleśń z oczu zgarną narody
**................**
Dalej **—** dalej **—** **—**

.zad. 4

* wawrzyn (a)
* ręce złamawszy na pancerz (a)
* gromnic płakaniem dziś polan (a)
* wieją proporce (a)
* budzenie się, zgarnięcie pleśni z oczu
* serca zmdlałe ocucą
* Przeogromna chorągiew, co się wśród dymów koleba (a)

Stosuje zabieg archaizacji, by nadać klimat starodawności tego pogrzebu

.zad. 5

* Temat: żałobny
* Gatunek: rapsod
* Motto: z Hannibala
* Nastrój: żałobny, dostojny, wysoki tworzony przez archaizację
* Rytm: monotonny, będący wynikiem zastosowania heksametru (próba)
* styl: podniosły, dla którego charakterystyczne są takie środki stylistyczne jak:
	** archaizmy
	** inwersja składniowa
	** aliteracja
	** onomatopeja
	** apostrofa
	** pytanie retoryczne

.zad. 6

* patrz: zad. 5
* --
* koptyjska
* tak

.zad 7

Biorąc pod uwagę wiersz Norwida "Bema pamięci rapsod żałosny", celem osoby wybitnej jest bycie prowodyrem postępu, przeczesującym nieznane tereny i sprawianie, że inni ludzie podejmują działania ku dobremu. Odnoszą się do tego wyrażenia typu "rumak, który spiętą włócznią przesadzi czarne czeluści", co może symbolizować walkę z analfabetyzmem (podobnie, jak średniowiecze jest nazywane ciemnymi wiekami).
