= Test 51

. Mężczyzna za kierownicą zielonej furgonetki nie mógł być naszym konsulem w Kijowie. W tym czasie konsul leciał do Aten.
.. The man behind the wheel of a green van couldn't have been our _ *(consul)* in Kiev. At the same time, the _ *(consul)* was flying to Athenes.
. Prawdę powiedziawszy, nie chce mi się rozmawiać teraz z ludźmi.
.. To tell the truth, I don't feel like talking to those people right now.
. Nie wolno ci myśleć tylko o sobie. Nikt nie będzie cię lubił. Z drugiej strony nie musisz wyrzekać się wszystkich przyjemności.
.. You ^aren't allowed to^ musn't think only about yourself. Nobody ^would^ will like you. On the other hand, you don't have to give up all your pleasures.
. Przyjedziemy posłuchać twoich uczniów pod warunkiem, że nie każą nam zostać do wieczora w firmie.
.. We'll come listen to your students, ^if they don't tell us^ provided that we're not told to stay in the ^office^ firm till the evening.
. Ani Helen ani ci spośród jej przyjaciół, którzy znają Franka, nie powinni tam teraz iść.
.. Neither Helen nor those among her friends should^n't^ go there right now.
. Czy teraz, po przeczytaniu tego artykułu, nadal myślisz, że oni będą mogli nam pomagać?
.. And now, having read that article, do you still think ^they're going^ they'll be able to help us?
. Czy znasz modelkę Molly Kay? Ona jest tą dziewczyną, z powodu której Max Perth stracił posadę na naszym uniwersytecie.
.. Do you know the model Molly Kay? She's that girl, because of whom Max Perth lost the job at our university.
. Trzeba chyba pomóc Ewie. Odkąd pokłóciła się z siostrą, gotuje dla nas wszystkich.
.. I think we need to help Eve. Ever since she got into an argument with her sister, she's been cooking for all of us.
. Przykro mi to powiedzieć, ale człowiek, którego tak uważnie wczoraj słuchaliście, jest kłamcą.
.. I'm sorry to tell you, but the man, that you listened to so carefully is a liar.
. Sue musi stale nosić ciemne okulary. Przez to nigdy nie jestem pewien, czy patrzy na mnie, czy nie.
.. Sue has to wear dark glasses constantly. Because of that, I ^don't know^ am not sure whether or not she's looking at me.
. Było dla mnie niespodzianką, że film zrobił wrażenie zarównio na dziennikarzach jak i naukowcach.
.. It was a surprise to me that the movie had impressed both the journalists and the scientists.
. Czy masz wyobrażenie, ile potrzebujemy czasu, żeby dokończyć parter?
.. Do you have any idea how much time we need to complete the ground floor?
. Myślałem że śnię, kiedy zobaczyłem, jak one zatrzymują swój samochód przed restauracją.
.. I thought I was dreaming, when I saw them stop their car in front of the restaurant.
. Do I drive today, or should I wait for you? Drive today. Tomorrow you won't be able to talk to the boss.
.. If you've invited mister Terry, who is the person least interested in new furniture, you should also invite the designer as well. I think I have his address.
