= Lekcja 7 - Writing an article - giving arguments for and against

It is a common misconception that you are required to attend a university of technology to get good technological education. We currently live in a society, where technology is ubiquitous, and therefore most major general universities (for example the University of Adam Mickiewicz in Poznan) have a pretty good IT profile. All things considered though, in the age of internet tutorials and bootcamps, is going to a university of technology (or a university in general) worthwhile?

Most employers, of course, attach great importance to hiring knowledgeable employees, that is why most jobs require a degree. That is not the case though with a lot of information technologies workplaces. Those firms prefer employing people with experience - sometimes not even job experience. If you have a lot of contributions to well known, open source projects; or have created and maintained many of such projects yourself, you will have a much better chance at getting hired than a person with a lot of theoretical knowledge, but without any experience in the field, that knowledge will ring hollow.

Zad. dom

1-8/26-27

.1/26

. muster up
. regurgitate the
. brushing
. keep
. manic
. wreck
. nerves
. through
. weight

.2/26

. summon
. faced
. come
. pile
. teetering
. standing

.3/26

. lighten
. boat
. hammered
. frazzled
. stride
. cold

.3/w40

. notched
. brush
. flits
. come
.

.5/w40

. without a doubt borrowed
. might encounter
. couldn't have been learning
. won't help
. could be getting ready

.9/w40

. having a good knowledge of
. may have already left
. must be feeling tired
. could've helped you with
. have made it in a hurry
. went through the roof
