= Lekcja 6

.Introduction

Of course, both homeschooling and formal education both have their own pros and drawbacks. Neither is perfect, and both are flawed. The general consensus is that homeschooling is time consuming for the parent, and formal education has a system flawed at the premise.

.Extension - Question 1

As I alluded to earlier, teaching your children yourself will take a lot of your time. Thus, homeschooling effectively prevents itself from being widely spread, as a lot of parents are just not capable of spending several hours a day to educate their children. Therefore, homeschooling is limited only to those families, where either at least one of the parents doesn't work or works at home.

.Extension - Question 2

The flaw at the premise of formal schooling is that it most definitely limits creativity. It's taking students and shaping them using a very cookie-cutter method that's not really been refined over the past centuries. It's teaching children to stick to the answer code and instead of expanding their hobbies, kids should worry about exams. It doesn't promote thinking - it promotes regurgitation.

.Extension - Question 3

To expand on my previous point, a lot of things schools teach young people are plainly useless. The topics are very synthetic, and often times they don't have real world applications. A prominent example of such is mathematics.

.Conclusion - Question 4

The education system is due for a reform - a deep one at that. The primary thing I would change, were I to make such a reform, is abolishing exams and making classes smaller. This way, the teachers will have to take care of so many students at once and they will be able to focus on kids more directly. Finally, I would call for abolishment of physical textbooks in favor of electronic textbooks (either by providing students shared devices or by BYOD initiative (Bring Your Own Device)).
